"""Added image_url to users

Revision ID: deb357170e4b
Revises: 6ce42c0cd817
Create Date: 2024-01-21 15:49:09.882082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb357170e4b'
down_revision = '6ce42c0cd817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('header_image_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('password', sa.Text(), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('password')
        batch_op.drop_column('location')
        batch_op.drop_column('bio')
        batch_op.drop_column('header_image_url')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
